# Header
menu:
  Home: /
  My Works: /works
  #Tags: /tags
  About: /about

rss: /atom.xml

# User Info
user_name: User Name
user_avatar: https://cdn2.iconfinder.com/data/icons/rcons-user/32/male-shadow-circle-512.png
user_location: Earth
user_description: "Hello World"
user_introduction: Here is introduction

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# 评论系统
use_livere: false
livere_uid: MTAyMC8yOTE4Ni81NzUz

use_disqus: true
disqus_url: https://haojen.disqus.com/embed.js

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
